import { Role } from '@prisma/client';

import { PERMISSIONS, Permission } from './permissions';

const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS)
  .flatMap(group => Object.values(group));

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,

  ADMIN: [
    ...Object.values(PERMISSIONS.USER),
    ...Object.values(PERMISSIONS.PROJECT),
    ...Object.values(PERMISSIONS.TASK),
    ...Object.values(PERMISSIONS.TEAM),
    ...Object.values(PERMISSIONS.CRM),
    ...Object.values(PERMISSIONS.DOCUMENT),
    PERMISSIONS.ANALYTICS.VIEW,
    PERMISSIONS.BILLING.MANAGE,
    PERMISSIONS.AI.USE,
  ],

  MANAGER: [
    PERMISSIONS.PROJECT.READ,
    PERMISSIONS.PROJECT.UPDATE,

    PERMISSIONS.TASK.READ,
    PERMISSIONS.TASK.CREATE,
    PERMISSIONS.TASK.UPDATE,
    PERMISSIONS.TASK.ASSIGN,
    PERMISSIONS.TASK.ARCHIVE,

    PERMISSIONS.CRM.READ,
    PERMISSIONS.CRM.WRITE,
    PERMISSIONS.CRM.MANAGE_PIPELINE,

    PERMISSIONS.TEAM.READ,

    PERMISSIONS.DOCUMENT.READ,
    PERMISSIONS.DOCUMENT.CREATE,
    PERMISSIONS.DOCUMENT.UPDATE,

    PERMISSIONS.ANALYTICS.VIEW,
    PERMISSIONS.AI.USE,
  ],

  EMPLOYEE: [
    PERMISSIONS.PROJECT.READ,

    PERMISSIONS.TASK.READ,
    PERMISSIONS.TASK.CREATE,
    PERMISSIONS.TASK.UPDATE,

    PERMISSIONS.CRM.READ,

    PERMISSIONS.DOCUMENT.READ,
    PERMISSIONS.DOCUMENT.CREATE,

    PERMISSIONS.AI.USE,
  ],
};
